server:
  port: 8080
  servlet:
    context-path: /demo #根路径名
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      ## 如果后端项目服务器和数据库服务器不在同一台主机，则需要修改localhost为数据库服务器ip地址
      url: jdbc:mysql://localhost:3306/fmmall?characterEncoding=utf-8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource #druid 连接池
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    ## log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.cailei.demo.entity # 扫描实体类包
  type-enums-package: com.cailei.demo.enums  # 配置扫描通用枚举
  mapper-locations: classpath*:mapper/**/*Mapper.xml # mapper文件路径
  global-config:
    banner: off # 关闭mybatis-plus启动图标
    # 逻辑删除配置
    db-config:
      logic-not-delete-value: 1  #删除前
      logic-delete-value: 0 #删除后
      logic-delete-field: isDelete #逻辑删除字段名
logging:
  level:
    root: info
    com.cailei.demo.mapper: debug
    io.swagger.models.parameters.AbstractSerializableParameter: error




